### ISSUE TITLE
Make pretty views

### ISSUE THREAD

**Issue by maria** [rosedu-hacks/GRails#13]
## TODOs
- [x]  Update the home page - use bootstrap to add colour and style
- [x] Add a header where we add home, about, sign up, sign in buttons
- [x] Add a header where we add home, sign_out buttons and other user stuff
- [x] Add a page to browse the forms
